# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: "0.9/test"
    schedule:
      interval: weekly
      day: friday
    groups:
      paperback:
        patterns:
          - "@paperback/toolchain"
          - "@paperback/types"
          - "@paperback/runtime-polyfills"
      minor-patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major